// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(opts) {
    var FORMS, app, common, db, forms, staff, _ref;

    if ((_ref = opts.login_url) == null) {
      opts.login_url = "/login";
    }
    app = opts.app;
    db = opts.db;
    forms = opts.forms || {};
    common = require("./common")(opts);
    staff = common.staff;
    FORMS = {
      pages: {
        print: 'paths',
        fields: [
          {
            name: 'title'
          }, {
            name: 'path'
          }, {
            name: 'content',
            type: 'textarea'
          }, {
            name: 'meta'
          }
        ]
      }
    };
    app.get("/admin/:collection", staff, function(req, res) {
      return db.collection(req.params.collection).find().toArray(function(err, records) {
        return res.render("admin/admin-list", {
          title: req.params.collection,
          form: forms[req.params.collection],
          req: req,
          email: req.session.email,
          records: records
        });
      });
    });
    app.get("/admin/:collection/:id", staff, function(req, res) {
      return db.collection(req.params.collection).findOne({
        _id: new ObjectId(req.params.id)
      }, function(err, rec) {
        return res.render("admin-object", {
          title: req.params.collection,
          req: req,
          form: forms[req.params.collection],
          email: req.session.email,
          rec: rec
        });
      });
    });
    return app.post("/admin/:collection/:id", staff, function(req, res) {
      return db.collection(req.params.collection).update({
        _id: new ObjectId(req.params.id)
      }, {
        $set: req.body
      }, function(err) {
        return res.redirect('/admin/' + req.params.collection);
      });
    });
  };

}).call(this);

/*
//@ sourceMappingURL=admin.map
*/
