//@ sourceMappingURL=index.map
// Generated by CoffeeScript 1.6.1
(function() {
  var admin, async, blog, fs, md5, users, uuid, videos;

  md5 = require('MD5');

  uuid = require('node-uuid');

  fs = require('fs');

  async = require('async');

  blog = require('./blog');

  videos = require('./videos');

  users = require('./users');

  admin = require('./admin');

  module.exports = {
    init: function(opts) {
      if (opts.videos) {
        videos(opts);
      }
      if (opts.blog) {
        blog(opts);
      }
      if (opts.users) {
        users(opts);
      }
      if (opts.admin) {
        admin(opts);
      }
      if (opts.blog) {
        return blog(opts);
      }
    },
    extend: function(obj) {
      Array.prototype.slice.call(arguments, 1).forEach(function(source) {
        var prop, _results;
        if (source) {
          _results = [];
          for (prop in source) {
            _results.push(obj[prop] = source[prop]);
          }
          return _results;
        }
      });
      return obj;
    }
  };

}).call(this);
