// Generated by CoffeeScript 1.6.2
(function() {
  var Mailer;

  Mailer = (function() {
    function Mailer() {}

    Mailer.prototype.send_mail = function(opts) {
      return console.log(opts);
    };

    return Mailer;

  })();

  module.exports.Mailer = Mailer;

}).call(this);

/*
//@ sourceMappingURL=base.map
*/
