// Generated by CoffeeScript 1.10.0
var Mailer;

Mailer = (function() {
  function Mailer(app) {
    this.app = app;
    this.default_from = (app.get('email_default_from')) || (app.get('admin_email')) || 'no-reply@example.com';
    this.default_from_name = (app.get('email_default_from_name')) || this.default_from;
  }

  Mailer.prototype.send_mail = function(opts) {
    return console.log(opts);
  };

  return Mailer;

})();

module.exports.Mailer = Mailer;
