// Generated by CoffeeScript 1.6.2
(function() {
  var Mailer;

  Mailer = (function() {
    function Mailer(app) {
      this.app = app;
      this.default_from = (app.get('email_default_from')) || (app.get('admin_email')) || 'no-reply@example.com';
    }

    Mailer.prototype.send_mail = function(opts) {
      return console.log(opts);
    };

    return Mailer;

  })();

  module.exports.Mailer = Mailer;

}).call(this);
