// Generated by CoffeeScript 1.6.2
(function() {
  var Mailer, base, util,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  base = require('./base');

  util = require('../../util');

  Mailer = (function(_super) {
    __extends(Mailer, _super);

    function Mailer(app) {
      Mailer.__super__.constructor.apply(this, arguments);
      this.sendgrid = new (require("sendgrid").SendGrid)(this.app.get('email_username'), this.app.get('email_password'));
    }

    Mailer.prototype.send_mail = function(opts, callback) {
      var defaults;

      defaults = {
        from: this.default_from,
        text: opts.body,
        headers: {
          'X-SMTPAPI': '{"category": ' + (this.app.get('name')) + '}'
        }
      };
      return this.sendgrid.send(util.extend({}, defaults, opts), function(success, message) {
        if (!success) {
          console.error(message);
        }
        return typeof callback === "function" ? callback(success, message) : void 0;
      });
    };

    return Mailer;

  })(base.Mailer);

  module.exports = function(app) {
    return app.set('mailer', new Mailer(app));
  };

}).call(this);

/*
//@ sourceMappingURL=sendgrid.map
*/
