// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app) {
    var db;

    db = app.get('db');
    return {
      staff: function(req, res, next) {
        if (req.session.email) {
          return db.collection('users').findOne({
            email: req.session.email,
            admin: true
          }, function(err, user) {
            if (user) {
              return next();
            } else {
              flash(req, 'error', 'Not authorized.');
              return res.redirect((app.get('login_url')) + "?then=" + req.path);
            }
          });
        } else {
          flash(req, 'error', 'Not authorized.');
          return res.redirect((app.get('login_url')) + "?then=" + req.path);
        }
      }
    };
  };

}).call(this);

/*
//@ sourceMappingURL=common.map
*/
