// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app) {
    var db, flash, login_url;

    db = app.get('db');
    flash = (require('../util')).flash;
    login_url = '/login';
    return {
      staff: function(req, res, next) {
        if (req.session.email) {
          return db.collection('users').findOne({
            email: req.session.email,
            admin: true
          }, function(err, user) {
            if (user) {
              return next();
            } else {
              flash(req, 'error', 'Not authorized.');
              return res.redirect(login_url + "?then=" + req.path);
            }
          });
        } else {
          flash(req, 'error', 'Not authorized.');
          return res.redirect(login_url + "?then=" + req.path);
        }
      }
    };
  };

}).call(this);
