// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app) {
    var db, flash;

    db = app.get('db');
    flash = function(req, message_type, message) {
      var m, _base, _ref, _ref1;

      if (message_type && message) {
        m = (_ref = (_base = req.session).messages) != null ? _ref : _base.messages = {};
        if ((_ref1 = m[message_type]) == null) {
          m[message_type] = [];
        }
        return m[message_type].push(message);
      }
    };
    return {
      flash: flash,
      staff: function(req, res, next) {
        if (req.session.email) {
          return db.collection('users').findOne({
            email: req.session.email,
            admin: true
          }, function(err, user) {
            if (user) {
              return next();
            } else {
              flash(req, 'error', 'Not authorized.');
              return res.redirect((app.get('login_url')) + "?then=" + req.path);
            }
          });
        } else {
          flash(req, 'error', 'Not authorized.');
          return res.redirect((app.get('login_url')) + "?then=" + req.path);
        }
      }
    };
  };

}).call(this);

/*
//@ sourceMappingURL=common.map
*/
