// Generated by CoffeeScript 1.10.0
var MongoStore, me, mongojs, session;

mongojs = require('mongojs');

session = require('express-session');

MongoStore = require('connect-mongo')(session);

me = module.exports = function(app) {
  var connect_string;
  if (!app.get('db_name')) {
    app.set('db_name', app.get('app_name'));
  }
  connect_string = app.get('db_name');
  app.set('db', mongojs(connect_string, [], {
    authMechanism: 'ScramSHA1'
  }));
  return app.use(session({
    secret: 'fkdowanvnsaijfij'
  }));
};

me.oid_str = function(inp) {
  return (me.oid(inp)).toString();
};

me.oid = function(inp) {
  var byte, result;
  if (inp instanceof mongojs.ObjectId) {
    return inp;
  } else if (inp.bytes) {
    result = ((function() {
      var i, len, ref, results;
      ref = inp.bytes;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        byte = ref[i];
        results.push(implied.util.zpad(byte.toString(16), 2));
      }
      return results;
    })()).join('');
    return mongojs.ObjectId(result);
  } else {
    return mongojs.ObjectId('' + inp);
  }
};
