// Generated by CoffeeScript 1.10.0
var fs, middleware, path;

fs = require('fs');

path = require('path');

middleware = {
  page: function(req, res, next) {
    var pagename;
    if ((req.method || req.originalMethod) !== 'GET') {
      return next();
    }
    pagename = req.path.substring(1).replace(/\/$/, '');
    return fs.exists(path.join(req.app.get('dir'), 'views', 'pages', pagename + '.jade'), function(exists) {
      if (exists) {
        return res.render(path.join('pages', pagename), {
          req: req
        });
      } else {
        return next();
      }
    });
  },
  cms: function(req, res, next) {
    var db, pagename;
    db = req.app.get('db');
    if ((req.method || req.originalMethod) !== 'GET') {
      return next();
    }
    pagename = req.path.substring(1).replace(/\/$/, '');
    return db.collection('cms').findOne({
      page: pagename
    }, function(err, page) {
      if (page) {
        return fs.exists(path.join(req.app.get('dir'), 'views', 'cms', pagename + '.jade'), function(exists) {
          if (exists) {
            return res.render(path.join('cms', pagename), page);
          } else {
            return res.render(path.join('cms', 'cms.jade'), page);
          }
        });
      } else {
        return next();
      }
    });
  }
};

module.exports = function(app) {
  app.use(middleware.cms);
  app.use(middleware.page);
  return app.set('view options', {
    layout: false
  });
};
