// Generated by CoffeeScript 1.10.0
var implied, requests;

implied = require('..');

requests = require('requests');

console.log('...');

describe('Hello World App', function() {
  console.log('...');
  return describe('setup app', function() {
    console.log('...');
    return it('was set up', function(done) {
      var app;
      app = implied();
      console.log('...');
      console.log('test');
      implied.mongo(app);
      implied.sendgrid(app);
      implied.boilerplate(app);
      expect(app.db).not.toEqual(void 0);
      expect(1).toBe(1);
      return setTimeout(function() {
        return done();
      });
    });
  });
});
